### ISSUE TITLE
flush() performance

### ISSUE THREAD

**Issue by derrick56007** [ppvk/libpen#2]
It seems like flush() is taking a really long time to draw (maybe it's the font drawing?). I can barely draw a 100x100 map under 250 ms. Perhaps we can look into optimizations for the drawing and test to see which part is the bottleneck.

*edit: I forgot to mention, nice library and thanks for making it! :+1:

**Comment by ppvk** [comment]
Hey, thanks for helping making it better. 
I've been playing with replacing our current two-canvas system with StageXL's Sprites, hopefully making things like font loading, text coloring, and flushing a bit faster and easier to grok. This would also pave the way for windows, panels, and buttons.

As for why our current flush() is taking so long, I think it's because it's refreshing the entire canvas every time instead of only the cells that need changing.  I'll push a fix for that after I merge your latest changes, and before I get too much further in this StageXL stuff.

**Comment by derrick56007** [comment]
I've been looking into [unicodetiles.js](http://tapiov.net/unicodetiles.js/) and found that it's really efficient. Right now I am using it instead of libpen but I'd rather stay with dart so I'll see what I can do to port it over. As for StageXL, I feel that it provides too much bloat in order to be used for a terminal/console/roguelike framework and while we should implement things such as buttons and panels, things other than tiles should be handled by the user.

**Comment by ppvk** [comment]
You're absolutely right. I started on it and realized the same thing. Also, on the topic of buttons and panels, I'm putting those in a separate library bundled with libpen. You can see my progress in the dev branch. 

flush() now only updates a tile if it needs it unlike before. I had some comments there saying that we were already doing that, but I must not have finished it before pushing. I'm going to close this issue for now.
